version: '2'
services:
  centos_nginx:
    tty: true
    image: studiomado/nginx:1.0
    ports:
      - 80:80
    volumes:
      - ./utils/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/web
    depends_on:
      - centos_php
  centos_php:
    tty: true
    image: studiomado/php71:1.1
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/web
    depends_on:
      - centos_mariadb
  centos_mariadb:
    tty: true
    image: studiomado/mariadb:1.0
    ports:
      - 3306:3306
	env_file:
	  - .env
